name: Tests
on: push
jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest
    container: python:3.12-slim-bookworm

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

    steps:

    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Install Python dependencies
      shell: bash -el {0}
      run: |
        pip install -r requirements.txt

    - name: Run tests
      shell: bash -el {0}
      run: |
        python -m unittest -v
