name: Tests
on: push
jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup stylua formatter
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 2.0.2
        args: --version

    - name: Lint lua sources
      run: |
        make lint

    - name: Check that lua func module pack last scripts version
      run: |
        make checkfunc

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      env:
        REDIS_PORT: ${{job.services.redis.ports[6379]}}
        REDIS_HOST: 'localhost'
        REDIS_DB: 0
      run: |
        make tests
