name: Tests
on: push
jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      env:
        REDIS_PORT: ${{job.services.redis.ports[6379]}}
        REDIS_HOST: 'localhost'
        REDIS_DB: 0
      run: |
        python -m unittest -v
